name: 'Release App'

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        required: true
        type: string

jobs:
  build-binaries:
    name: 'Build binary'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache rust compiled binaries
        uses: actions/cache@v3
        with:
          path: ./src-tauri/target
          key: rust-compiled-binaries-${{ hashFiles('./src-tauri/Cargo.lock') }}
          restore-keys: |
            rust-compiled-binaries-
 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev \
              build-essential \
              curl \
              wget \
              file \
              libssl-dev \
              libgtk-3-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev

      - run: yarn

      - name: Build App
        run: yarn tauri build

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "./src-tauri/target/release/parch-wiki"

  publish:
    name: 'Create release'
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      RELEASE_TAG: ${{ inputs.releaseTag }}
      REPO_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - name: 'Remove previous releases with ${{ env.RELEASE_TAG }} tag if exists'
        continue-on-error: true
        run: gh release delete $RELEASE_TAG --cleanup-tag -R $REPO_NAME

      - name: 'Create new release'
        run: gh release create -R $REPO_NAME $RELEASE_TAG ./artifacts/*
