name: 'Release App'

on:
  push:
    branches:
      - workflow-refactor-test

jobs:
  build-binaries:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache rust compiled binaries
        uses: actions/cache@v3
        with:
          path: ./src-tauri/target
          key: rust-compiled-binaries-${{ hashFiles('./src-tauri/Cargo.lock') }}
          restore-keys: |
            rust-compiled-binaries-
 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Build Frontend
        run: yarn && yarn generate

      - name: Build App
        run: yarn tauri build

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "./src-tauri/target/release/parch-wiki"

  Publish:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: 'create release'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create -R ${{ github.repository }} 1.0.0 ./artifacts/*
